// TODO: Complete descriptions for all the studios

/**
 * Enum representing different animation studios.
 * The keys are internal identifiers, and the values are the corresponding names of the animation studios.
 *
 * This enum is useful for categorizing and referencing animation studios in a structured manner.
 * Each entry represents a specific animation studio, providing an easy way to access studio names
 * throughout the library.
 */
export enum Studio {

    UNKNOWN = "Sconosciuto",

    /**
     * Shiyong Wang founded [2:10 Animation](https://en.2-10.cn/) as a small studio in 2007, Wuhan, China. After dedicating to Chinese
     * animation for 16 years, the company now has more than 500 employees offering a package service of cartoon IP
     * production and operation. Their services include 6 complete and independent industrial chain modules including
     * animation project planning, script creation, animation production, R&D, publicity and distribution, and
     * commercial operation. They maintain strategic cooperation with leading companies of film and television, video,
     * novel, game, and consumer goods industries, etc.
     *
     * Their works are of multiple categories. It has more than ten high-quality original popular IPs such as
     * "The Silver Guardian", "I am Joybo", "The Great Warrior Wall", "Glaze War" and "The Country of Rare Treasures".
     * They continue to produce high-quality CG short films for dozens of international game products such as
     * "League of Legends", "Onmyoji", "Arknights", "Honor of Kings", "Harry Potter: Magic Awakened". And they have
     * created animation series for many popular IPs such as "Close Combat Mage", "Thousands of World",
     * "Everlasting God of Sword", "Lighter and Princess Dress".
     *
     * While being recognized by the market and users, they have won the recognition and investment of Alibaba,
     * Pop Mart, Frees Fund, COL Group, HyperGryph and other companies and institutions.
     *
     * In 2022, in addition to continuing in-depth cooperation with more than 30 game companies, they also participated
     * in the production of many well-known animation IPs such as "Digimon" and "Transformers" and so on.
     */
    TWOTEN_ANIMATION = "2:10 AM Animation",

    /**
     * We couldn't find much about this studio. We know they have worked on titles like "Megalobox", "Sweetness &
     * Lightning", "The Pilot's Love Song" and "Actually, I am...".
     *
     * The studio seems to have changed their name to TMS/3xCube. They were referred to as 東京ムービー/3xCube in the past.
     *
     * @link [TMS Website](https://tmsanime.com/)
     * @link [Wikipedia](https://en.wikipedia.org/wiki/TMS_Entertainment)
     */
    TRIPLEXCUBE = "3xCube",

    /**
     * Sadly we weren't able to find official information about this studio.
     *
     * According to [AnimeNewsNetwork](https://www.animenewsnetwork.com), in
     * [this article](https://www.animenewsnetwork.com/encyclopedia/company.php?id=21406), the company has worked on
     * a number of titles, some of which are pretty well known, namely "Attack on Titan Final Season THE FINAL CHAPTERS
     * (TV)", "Attack on Titan The Final Season Part 2 (TV)", "Chainsaw Man (TV)", "Josee, The Tiger and the Fish
     * (movie)", "Psycho-Pass 3: First Inspector (movie)" and "Trigun Stampede (TV)".
     */
    FIVE_INCORPORATED = "5 Inc.",

    /**
     * According to [Wikipedia](https://wikipedia.org) in
     * [this article](https://en.wikipedia.org/wiki/Eight_Bit_(studio)):
     *
     * Eightbit co., Ltd. (Japanese: 株式会社エイトビット, Hepburn: Kabushiki-gaisha Eitobitto), also known as 8bit, is a
     * Japanese animation studio established in September 2008 by former Satelight members.
     *
     * On June 8, 2020, it was announced that Eight Bit had entered a partnership with Bandai Namco to create multiple
     * anime productions. Their first project will be The Slime Diaries: That Time I Got Reincarnated as a Slime.
     *
     * On November 1, 2021, Eight Bit opened a new studio in the Niigata Prefecture.
     *
     * On April 1, 2024, Eight Bit became a wholly owned subsidiary of Bandai Namco Filmworks.
     *
     * According to [AniDB](https://anidb.net) on [this page](https://anidb.net/creator/21883) and
     * [MyAnimeList](https://myanimelist.net/) on [this page](https://myanimelist.net/anime/producer/441/8bit):
     *
     * Eight Bit was originally Satelight's first studio and was involved in the production of several works including
     * "Noein", "Sousei no Aquarion" and "Macross F". It became independent in September 2008 under producer Kasai
     * Tsutomu. Its headquarters is located in Suginami, Tokyo, Japan. The major line of work is planning and production
     * of animation programs and 3DCG work.
     *
     * The studio's first major production was the "Gekijouban Macross F: Itsuwari no Utahime" feature film in
     * collaboration with the former parent company Satelight in 2009. The first major work on its own was the
     * television anime series "IS: Infinite Stratos" in 2011.
     *
     * @link [Official Website](https://8bit-studio.co.jp)
     */
    EIGHT_BIT = "8bit",

    A1_PICTURES= "A-1 Pictures",
    A_LINE = "A-Line",
    A_REAL = "A-Real",
    A_C_G_T = "A.C.G.T.",
    A24 = "A24",
    ABC_ANIMATION = "ABC Animation",
    ABJ_COMPANY = "ABJ COMPANY",
    ACCA_EFFE = "Acca effe",
    ACTAS = "Actas",
    AIC = "AIC",
    AIC_A_S_T_A = "AIC A.S.T.A.",
    AIC_BUILD = "AIC Build",
    AIC_CLASSIC = "AIC Classic",
    AIC_FRONTIER = "AIC Frontier",
    AIC_PLUS = "AIC Plus+",
    AIC_SPIRITS = "AIC Spirits",
    AJIA_DO = "Ajia-Do",
    AKATSUKI = "Akatsuki",
    ALBACROW = "Albacrow",
    AN_DERCEN = "An DerCen",
    ANIMA = "Anima",
    ANIMA_CO = "Anima&Co.",
    ANIMATE_FILM = "animate Film",
    ANIMATION_DO = "Animation Do",
    ANKAMA_ANIMATIONS = "Ankama Animations",
    ANPRO = "Anpro",
    APPP = "APPP",
    AQUA_ARIS = "AQUA ARIS",
    ARECT = "ARECT",
    ARK = "Ark",
    ARMS = "Arms",
    ARTLAND = "Artland",
    ARTMIC = "Artmic",
    ARVO_ANIMATION = "Arvo Animation",
    ASAHI_PRODUCTION = "Asahi Production",
    ASATSU_DK = "Asatsu DK",
    ASCENSION = "Ascension",
    ASHI_PRODUCTION = "Ashi Production",
    ASK_ANIMATION_STUDIO = "ASK Animation Studio",
    ASREAD = "Asread",
    ATELIERPONTDARC = "AtelierPontdarc",
    AVACO_CREATIVE_STUDIOS = "Avaco Creative Studios",
    AXSIZ = "AXsiZ",
    B_CMAY_PICTURES = "B.CMAY PICTURES",
    B_T = "B&T",
    BAKKEN_RECORD = "Bakken Record",
    BANDAI_NAMCO_PICTURES = "Bandai Namco Pictures",
    BARNUM_STUDIO = "Barnum Studio",
    BEE_MEDIA = "Bee Media",
    BEE_TRAIN = "Bee Train",
    BESTACK = "BeSTACK",
    BIBURY_ANIMATION_CG = "Bibury Animation CG",
    BIBURY_ANIMATION_STUDIOS = "Bibury Animation Studios",
    BIGFIREBIRD_ANIMATION = "BigFireBird Animation",
    BLADE = "Blade",
    BLOOMZ = "BloomZ",
    BONES = "Bones",
    BOOKONG_CULTURE = "BooKong Culture",
    BOUNCY = "Bouncy",
    BRAINS_BASE = "Brain's Base",
    BRIDGE = "Bridge",
    BRIO_ANIMATION = "Brio Animation",
    BUEMON = "Buemon",
    BUG_FILMS = "BUG FILMS",
    C_STATION = "C-Station",
    C2C = "C2C",
    CG_YEAR = "CG Year",
    CGCG_STUDIO = "CGCG Studio",
    CHAOS_PROJECT = "Chaos Project",
    CHENGDU_COCO_CARTOON = "Chengdu Coco Cartoon",
    CHILDRENS_PLAYGROUND_ENTERTAINMENT = "Children's Playground Entertainment",
    CLAP = "CLAP",
    CLOUD_HEARTS = "Cloud Hearts",
    CLOVERWORKS = "CloverWorks",
    CMC_MEDIA = "CMC Media",
    COCKTAIL_MEDIA = "Cocktail Media",
    COLORED_PENCIL_ANIMATION_DESIGN = "Colored-Pencil Animation Design",
    COMIX_WAVE_FILMS = "CoMix Wave Films",
    COMPTOWN = "CompTown",
    CONNECT = "Connect",
    CRAFTAR_STUDIOS = "Craftar Studios",
    CREATORS_IN_PACK = "Creators in Pack",
    CYGAMESPICTURES = "CygamesPictures",
    DANDELION_ANIMATION_STUDIO = "DandeLion Animation Studio",
    DAUME = "Daume",
    DAVID_PRODUCTION = "David Production",
    DIGITAL_NETWORK_ANIMATION = "Digital Network Animation",
    DIOMEDEA = "Diomedea",
    DJINN_POWER = "Djinn Power",
    DLE = "DLE",
    DMM_PICTURES = "DMM pictures",
    DMM_FUTUREWORKS = "DMM.futureworks",
    DOGA_KOBO = "Doga Kobo",
    DOMERICA = "domerica",
    DONGWOO_A_E = "Dongwoo A&E",
    DR_MOVIE = "DR Movie",
    DRAWIZ = "DRAWIZ",
    DRIVE = "Drive",
    DROP = "drop",
    DWANGO = "Dwango",
    DYNAMO_PICTURES = "Dynamo Pictures",
    E_G_FILMS = "E&G Films",
    E_H_PRODUCTION = "E&H Production",
    EAST_FISH_STUDIO = "East Fish Studio",
    EGG_FIRM = "Egg Firm",
    EIKEN = "Eiken",
    EKACHI_EPILKA = "EKACHI EPILKA",
    ELIAS = "Elias",
    EMON = "Emon",
    EMT_SQUARED = "EMT Squared",
    ENCOURAGE_FILMS = "Encourage Films",
    ENGI = "ENGI",
    ENISHIYA = "Enishiya",
    EOTA = "EOTA",
    ETHER_KITTEN = "Ether Kitten",
    EVG = "evg",
    EZOLA = "Ezόla",
    FANWORKS = "Fanworks",
    FEEL = "feel.",
    FELIX_FILM = "Felix Film",
    FIFTH_AVENUE = "Fifth Avenue",
    FLAGSHIP_LINE = "FLAGSHIP LINE",
    FLAT_STUDIO = "Flat Studio",
    FREDERATOR_STUDIOS = "Frederator Studios",
    FRONT_LINE = "Front Line",
    FRONTIER_WORKS = "Frontier Works",
    FUGAKU = "Fugaku",
    FUJI_TV = "Fuji TV",
    G_ANGLE = "G-angle",
    G_G_ENTERTAINMENT = "G&G Entertainment",
    GAINA = "Gaina",
    GAINAX = "Gainax",
    GAINAX_KYOTO = "Gainax Kyoto",
    GALLOP = "Gallop",
    GARDEN_CULTURE = "Garden Culture",
    GATHERING = "Gathering",
    GEEK_TOYS = "GEEK TOYS",
    GEKKOU = "Gekkou",
    GEMBA = "GEMBA",
    GENO_STUDIO = "Geno Studio",
    GIFTANIMATION = "GIFTanimation",
    GIGA_PRODUCTION = "Giga Production",
    GINGA_YA = "Ginga Ya",
    GOHANDS = "GoHands",
    GONZO = "Gonzo",
    GOSAY_STUDIO = "Gosay Studio",
    GRAPHINICA = "Graphinica",
    GRAVITY_WELL = "Gravity Well",
    GREEN_MONSTER_TEAM = "Green Monster Team",
    GRIZZLY = "GRIZZLY",
    GROUP_TAC = "Group TAC",
    GUTON_ANIMATION_STUDIO = "Guton Animation Studio",
    HAL_FILM_MAKER = "Hal Film Maker",
    HAOLINERS_ANIMATION_LEAGUE = "Haoliners Animation League",
    HAYABUSA_FILM = "Hayabusa Film",
    HMCH = "HMCH",
    HOODS_DRIFTERS_STUDIO = "Hoods Drifters Studio",
    HOODS_ENTERTAINMENT = "Hoods Entertainment",
    HORNETS = "HORNETS",
    HOTLINE = "Hotline",
    HOTZIPANG = "HOTZIPANG",
    HUAMEI_ANIMATION = "HuaMei Animation",
    ILCA = "ILCA",
    IMAGICA_LAB = "Imagica Lab.",
    IMAGIN = "Imagin",
    IMAGINEER = "Imagineer",
    INDIVISION = "Indivision",
    ISSEN = "Issen",
    IXTL = "ixtl",
    J_C_STAFF = "J.C.Staff",
    JAPAN_TAPS = "Japan Taps",
    JAPAN_VISTEC = "Japan Vistec",
    JINNIS_ANIMATION_STUDIOS = "Jinnis Animation Studios",
    JUMONDO = "Jumondo",
    KACHIDOKI_STUDIO = "Kachidoki Studio",
    KACHIGARASU = "Kachigarasu",
    KAMIKAZE_DOUGA = "Kamikaze Douga",
    KARAKU = "Karaku",
    KAZAMI_GAKUEN_KOUSHIKI_DOUGA_BU = "Kazami Gakuen Koushiki Douga-bu",
    KHARA = "Khara",
    KIGUMI = "Kigumi",
    KINEMA_CITRUS = "Kinema Citrus",
    KINO_PRODUCTION = "Kino Production",
    KJJ_ANIMATION = "KJJ Animation",
    KOKUSAI_EIGASHA = "Kokusai Eigasha",
    KUNGFUFROG_ANIMATION = "Kungfufrog Animation",
    KYOTO_ANIMATION = "Kyoto Animation",
    KYOTOMA = "Kyotoma",
    LANDQ_STUDIOS = "LandQ studios",
    LAPIN_TRACK = "Lapin Track",
    LARX_ENTERTAINMENT = "Larx Entertainment",
    LAY_DUCE = "Lay-duce",
    LERCHE = "Lerche",
    LESPRIT = "Lesprit",
    LIBER = "Liber",
    LICO = "LICO",
    LIDE = "Lide",
    LIDENFILMS = "LIDENFILMS",
    LIDENFILMS_KYOTO_STUDIO = "LIDENFILMS Kyoto Studio",
    LIFE_WORK = "Life Work",
    LIGHT_CHASER_ANIMATION_STUDIOS = "Light Chaser Animation Studios",
    LILIX = "Lilix",
    LINGSANWU_ANIMATION = "Lingsanwu Animation",
    LIVE2D_CREATIVE_STUDIO = "Live2D Creative Studio",
    LMD = "LMD",
    M_S_C = "M.S.C",
    MADHOUSE = "Madhouse",
    MAGIA_DORAGLIER = "Magia Doraglier",
    MAGIC_BUS = "Magic Bus",
    MAHO_FILM = "Maho Film",
    MAKARIA = "Makaria",
    MANAA_ANIMATION = "Manaa Animation",
    MANGLOBE = "Manglobe",
    MAPPA = "MAPPA",
    MARVY_JACK = "Marvy Jack",
    MARZA_ANIMATION_PLANET = "Marza Animation Planet",
    MASTER_LIGHTS = "MASTER LIGHTS",
    MIHOYOANIME = "miHoYoAnime",
    MILI_PICTURES = "Mili Pictures",
    MILLEPENSEE = "Millepensee",
    MINAMI_MACHI_BUGYOUSHO = "Minami Machi Bugyousho",
    MIPPEI_EIGEKI_KIRYUUKAN = "Mippei Eigeki Kiryuukan",
    MONOFILMO = "monofilmo",
    MUA_FILM = "Mua Film",
    MUSHI_PRODUCTION = "Mushi Production",
    NAKAMURA_PRODUCTION = "Nakamura Production",
    NAMU_ANIMATION = "Namu Animation",
    NAZ = "NAZ",
    NETFLIX_ANIMATION = "Netflix Animation",
    NEXUS = "Nexus",
    NICE_BOAT_ANIMATION = "Nice Boat Animation",
    NIHON_AD_SYSTEMS = "Nihon Ad Systems",
    NIPPON_ANIMATION = "Nippon Animation",
    NOMAD = "Nomad",
    NUT = "Nut",
    OFFICE_DCI = "Office DCI",
    OFFICE_NOBU = "Office Nobu",
    OKURUTO_NOBORU = "Okuruto Noboru",
    OLM = "OLM",
    OLM_DIGITAL = "OLM Digital",
    ORANGE = "Orange",
    ORDET = "Ordet",
    OXYBOT = "Oxybot",
    OZ = "Oz",
    P_A_WORKS = "P.A. Works",
    P_I_C_S = "P.I.C.S.",
    PALM_STUDIO = "Palm Studio",
    PANDA_TOWER_STUDIO = "Panda Tower Studio",
    PAPER_PLANE_ANIMATION_STUDIO_ANIME = "Paper Plane Animation Studio Anime",
    PASSIONE = "Passione",
    PASTEL = "Pastel",
    PB_ANIMATION_CO_LIMITED = "Pb Animation Co. Ltd.",
    PHANTOM = "PHANTOM",
    PICTURE_MAGIC = "Picture Magic",
    PIERROT_FILMS = "Pierrot Films",
    PIERROT_PLUS = "Pierrot Plus",
    PINE_JAM = "Pine Jam",
    PLANET = "Planet",
    PLATINUM_VISION = "Platinum Vision",
    PLUM = "Plum",
    POLYGON_PICTURES = "Polygon Pictures",
    POWERHOUSE_ANIMATION_STUDIOS = "Powerhouse Animation Studios",
    PRA = "PRA",
    PRIMASTEA = "Primastea",
    PRIMETIME = "PrimeTime",
    PRODUCTION_H = "Production +h.",
    PRODUCTION_DOA = "production doA",
    PRODUCTION_GOODBOOK = "Production GoodBook",
    PRODUCTION_I_G = "Production I.G",
    PRODUCTION_IMS = "Production IMS",
    PRODUCTION_REED = "Production Reed",
    PROJECT_51_PRODUCTIONS = "Project 51 Productions",
    PROJECT_NO_9 = "Project No.9",
    PUBLIC_AND_BASIC = "Public & Basic",
    PURPLE_COW_STUDIO_JAPAN = "Purple Cow Studio Japan",
    QUAD = "Quad",
    QUALIA_ANIMATION = "Qualia Animation",
    QUBIC_PICTURES = "Qubic Pictures",
    RABBIT_GATE = "Rabbit Gate",
    RADIX = "Radix",
    RED_DOG_CULTURE_HOUSE = "Red Dog Culture House",
    REMIC = "Remic",
    REVOROOT = "Revoroot",
    RISING_FORCE = "Rising Force",
    ROCKWELL_EYES = "Rockwell Eyes",
    ROLL2 = "ROLL2",
    RUO_HONG_CULTURE = "Ruo Hong Culture",
    SABER_WORKS = "Saber Works",
    SAETTA = "Saetta",
    SAMSARA_ANIMATION_STUDIO = "Samsara Animation Studio",
    SANZIGEN = "SANZIGEN",
    SATELIGHT = "Satelight",
    SCIENCE_SARU = "Science SARU",
    SCOOTER_FILMS = "Scooter Films",
    SEVEN = "Seven",
    SEVEN_ARCS = "Seven Arcs",
    SEVEN_ARCS_PICTURES = "Seven Arcs Pictures",
    SEVEN_STONE_ENTERTAINMENT = "Seven Stone Entertainment",
    SHAFT = "Shaft",
    SHANGHAI_FOCH_FILM_CULTURE_INVESTMENT = "Shanghai Foch Film Culture Investment",
    SHANKAR_ANIMATION = "Shankar Animation",
    SHAREFUN_STUDIO = "Sharefun Studio",
    SHIN_EI_ANIMATION = "Shin-Ei Animation",
    SHINKUUKAN = "Shinkuukan",
    SHIROGUMI = "Shirogumi",
    SHUKA = "Shuka",
    SIGNAL_MD = "Signal.MD",
    SILVER = "Silver",
    SILVER_LINK = "Silver Link.",
    SOLA_DIGITAL_ARTS = "Sola Digital Arts",
    SOTSU = "Sotsu",
    SPACE_NEKO_COMPANY = "Space Neko Company",
    SPARKLY_KEY_ANIMATION_STUDIO = "Sparkly Key Animation Studio",
    SPRITE_ANIMATION_STUDIOS = "Sprite Animation Studios",
    STAPLE_ENTERTAINMENT = "Staple Entertainment",
    STEVE_N_STEVEN = "Steve N'Steven",
    STINGRAY = "Stingray",
    STUDIO_3HZ = "Studio 3Hz",
    STUDIO_4_C = "Studio 4°C",
    STUDIO_A_CAT = "Studio A-CAT",
    STUDIO_ANIMAL = "Studio Animal",
    STUDIO_BIND = "Studio Bind",
    STUDIO_BLANC = "Studio Blanc",
    STUDIO_CHIZU = "Studio Chizu",
    STUDIO_COLORIDO = "Studio Colorido",
    STUDIO_COMET = "Studio Comet",
    STUDIO_DAISY = "Studio Daisy",
    STUDIO_DEEN = "Studio Deen",
    STUDIO_DURIAN = "Studio DURIAN",
    STUDIO_ELLE = "Studio elle",
    STUDIO_FANTASIA = "Studio Fantasia",
    STUDIO_FLAD = "Studio Flad",
    STUDIO_FLAG = "Studio Flag",
    STUDIO_GHIBLI = "Studio Ghibli",
    STUDIO_GOKUMI = "Studio Gokumi",
    STUDIO_HIBARI = "Studio Hibari",
    STUDIO_HOKIBOSHI = "Studio Hokiboshi",
    STUDIO_JEMI = "Studio Jemi",
    STUDIO_JUNIO = "Studio Junio",
    STUDIO_KAFKA = "Studio Kafka",
    STUDIO_KAI = "Studio Kai",
    STUDIO_KIKAN = "Studio Kikan",
    STUDIO_LAN = "Studio LAN",
    STUDIO_LINGS = "Studio Lings",
    STUDIO_LIVE = "Studio Live",
    STUDIO_M2 = "Studio M2",
    STUDIO_MASSKET = "Studio Massket",
    STUDIO_MATRIX = "Studio Matrix",
    STUDIO_MAUSU = "Studio Mausu",
    STUDIO_MIR = "Studio Mir",
    STUDIO_MOE = "Studio Moe",
    STUDIO_MOTHER = "studio MOTHER",
    STUDIO_N = "Studio N",
    STUDIO_NANAHOSHI = "Studio Nanahoshi",
    STUDIO_PALETTE = "Studio Palette",
    STUDIO_PIERROT = "Studio Pierrot",
    STUDIO_POLON = "Studio Polon",
    STUDIO_PONOC = "Studio Ponoc",
    STUDIO_PPURI = "Studio Ppuri",
    STUDIO_PUYUKAI = "Studio PuYUKAI",
    STUDIO_RIKKA = "Studio Rikka",
    STUDIO_SIGNPOST = "Studio Signpost",
    STUDIO_VOLN = "Studio VOLN",
    STUDIO_CUCURI = "Studio! Cucuri",
    SUBLIMATION = "Sublimation",
    SUCCESS_CORPORATION = "Success Corp.",
    SUISEISHA = "Suiseisha",
    SUNRISE = "Sunrise",
    SUNRISE_BEYOND = "Sunrise Beyond",
    SYNERGYSP = "SynergySP",
    TAMA_PRODUCTION = "Tama Production",
    TATSUNOKO_PRODUCTION = "Tatsunoko Production",
    TEAM_ONEONE = "Team OneOne",
    TEAM_TILLDAWN = "Team TillDawn",
    TEAM_YAMAHITSUJI = "Team Yamahitsuji",
    TEAM_YOKKYUFUMAN = "Team YokkyuFuman",
    TEAMKG = "teamKG",
    TEAR_STUDIO = "Tear Studio",
    TEDDY = "Teddy",
    TELE_CARTOON_JAPAN = "Tele-Cartoon Japan",
    TELECOM_ANIMATION_FILM = "Telecom Animation Film",
    TENCENT_ANIMATION_AND_COMICS = "Tencent Animation & Comics",
    TENCENT_PENGUIN_PICTURES = "Tencent Penguin Pictures",
    TEZUKA_PRODUCTIONS = "Tezuka Productions",
    THE_ANSWER_STUDIO = "The Answer Studio",
    THINK_CORPORATION = "Think Corporation",
    THUNDRAY = "Thundray",
    THYMOS_MEDIA = "Thymos Media",
    TMS_ENTERTAINMENT = "TMS Entertainment",
    TNK = "TNK",
    TOEI_ANIMATION = "Toei Animation",
    TOHO_ANIMATION = "TOHO animation",
    TOHO_INTERACTIVE_ANIMATION = "Toho Interactive Animation",
    TOKYO_KIDS = "Tokyo Kids",
    TOKYO_MOVIE_SHINSHA = "Tokyo Movie Shinsha",
    TOMASON = "Tomason",
    TOMOVIES = "Tomovies",
    TOPCRAFT = "Topcraft",
    TRANS_ARTS = "Trans Arts",
    TRI_SLASH = "Tri-Slash",
    TRIANGLE_STAFF = "Triangle Staff",
    TRIF_STUDIO = "TriF Studio",
    TRIGGER = "Trigger",
    TRINET_ENTERTAINMENT = "Trinet Entertainment",
    TROYCA = "TROYCA",
    TSUCHIDA_PRODUCTIONS = "Tsuchida Productions",
    TSUMUGI_AKITA_ANIMATION_LAB = "Tsumugi Akita Animation Lab",
    TWILIGHT_STUDIO = "Twilight Studio",
    TWIN_ENGINE = "Twin Engine",
    TYO_ANIMATIONS = "TYO Animations",
    TYPHOON_GRAPHICS = "Typhoon Graphics",
    UFOTABLE = "ufotable",
    UNEND = "Unend",
    URBAN_PRODUCT = "Urban Product",
    UWAN_PICTURES = "UWAN Pictures",
    VEGA_ENTERTAINMENT = "Vega Entertainment",
    VENET = "Venet",
    VISUAL_FLIGHT = "Visual Flight",
    VOIL = "Voil",
    W_TOON_STUDIO = "W-Toon Studio",
    WAO_WORLD = "WAO World",
    WAWAYU_ANIMATION = "Wawayu Animation",
    WHITE_FOX = "White Fox",
    WINDY_STUDIO = "Windy Studio",
    WIT_STUDIO = "Wit Studio",
    WOLFSBANE = "Wolfsbane",
    XEBEC = "Xebec",
    XFLAG = "XFLAG",
    XIAOYING_FEIYANG_PICTURES = "Xiaoying Feiyang Pictures",
    YAOYOROZU = "Yaoyorozu",
    YOKOHAMA_ANIMATION_LAB = "Yokohama Animation Lab",
    YOSTAR_PICTURES = "Yostar Pictures",
    YUMETA_COMPANY = "Yumeta Company",
    ZERO_G = "Zero-G",
    ZERO_G_ROOM = "Zero-G Room",
    ZEXCS = "Zexcs"
}